name: CI Build

on:
  workflow_dispatch:
  push:
    paths:
      - 'include/**'
      - 'src/**'
      - 'CameBoy/**'
      - '.github/workflows/cameboy.yml'
  pull_request:
    paths:
      - 'include/**'
      - 'src/**'
      - 'CameBoy/**'
      - '.github/workflows/cameboy.yml'

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Cache CPM modules ---
      - name: Cache CPM modules
        id: cache-cpm
        uses: actions/cache@v4
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ matrix.os }}-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
          restore-keys: |
            ${{ runner.os }}-cpm-

      # --- Set up ccache via GitHub Action ---
      - name: Set up ccache (Linux/macOS)
        if: matrix.os != 'windows-latest'
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true
          key: ${{ github.workflow }}-ccache-${{ matrix.os }}

      # --- Install dependencies based on OS ---
      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libsdl2-dev libfreetype6-dev libsdl2-ttf-dev

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install sdl2 freetype sdl2_ttf

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          vcpkg install sdl2:x64-windows sdl2-ttf:x64-windows freetype:x64-windows
          echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" >> $env:GITHUB_ENV

      # --- Configure with CMake based on OS ---
      - name: Configure project with CMake (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: |
          mkdir -p build && cd build
          cmake -DCMAKE_BUILD_TYPE=Debug \
                -DCPM_SOURCE_CACHE=${CPM_SOURCE_CACHE} \
                -DCMAKE_C_COMPILER_LAUNCHER=ccache \
                -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
                ../CameBoy

      - name: Configure project with CMake (Windows)
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ^
                -DCPM_SOURCE_CACHE=%CPM_SOURCE_CACHE% ^
                -DCPM_USE_LOCAL_PACKAGES=ON ^
                -DCMAKE_TOOLCHAIN_FILE="%VCPKG_INSTALLATION_ROOT%\scripts\buildsystems\vcpkg.cmake" ^
                ..\CameBoy

      # --- Build project ---
      - name: Build project
        run: cmake --build build -j4
