name: CameBoy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Cache CPM modules ---
      - name: Cache CPM modules
        id: cache-cpm
        uses: actions/cache@v4
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
          restore-keys: |
            ${{ runner.os }}-cpm-

      # --- Set up ccache via GitHub Action ---
      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true

      # --- Configure, build, and run ---
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libsdl2-dev libfreetype6-dev libsdl2-ttf-dev

      - name: Configure project with CMake
        run: |
          mkdir -p build && cd build
          cmake -DCMAKE_BUILD_TYPE=Debug \
                -DCPM_SOURCE_CACHE=${CPM_SOURCE_CACHE} \
                -DCMAKE_C_COMPILER_LAUNCHER=ccache \
                -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
                ../CameBoy

      - name: Build project
        run: cmake --build build -j4
